In [2]:
import torch, numpy as np
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from transformers import is_torch_available

print(torch.__version__)
print(is_torch_available())

2.2.0
True


In [2]:

x = torch.rand(5, 4)
print(x)

tensor([[0.6048, 0.9235, 0.3119, 0.8400],
        [0.6840, 0.3278, 0.1575, 0.6626],
        [0.3146, 0.5690, 0.6558, 0.8794],
        [0.9118, 0.4601, 0.7932, 0.3451],
        [0.2707, 0.0791, 0.9626, 0.4776]])


In [3]:
import os
import time
import datetime
import numpy as np
import random
from tqdm import tqdm
import torch
from torch.utils.data import Dataset, DataLoader, random_split, RandomSampler
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers import AdamW, get_linear_schedule_with_warmup

In [4]:
if torch.cuda.is_available():
    print("Usar GPU")
    device = torch.device("cuda")
    batch_size = 3
else:
    print("usar CPU")
    device = torch.device("cpu")
    batch_size = 1

usar CPU


In [5]:
ndarray = np.array([0, 1, 2])
print(ndarray)

[0 1 2]


In [6]:
t = torch.from_numpy(ndarray)
print(t)

tensor([0, 1, 2], dtype=torch.int32)


In [7]:
print(t.shape)
print(t.dtype)
print(t.device)

torch.Size([3])
torch.int32
cpu


In [8]:
ndarray = np.array([[0, 1, 2], [3, 4, 5]])
t = torch.from_numpy(ndarray)
print(t)

tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32)


In [9]:
new_t = torch.rand_like(t, dtype=torch.float)
print(new_t)

tensor([[0.0750, 0.4752, 0.2450],
        [0.4695, 0.1930, 0.2320]])


In [10]:
list_a = [1, 2, 3, 4]

# Create a tensor from list_a
tensor_a = torch.tensor(list_a)
print(tensor_a)

tensor([1, 2, 3, 4])


In [11]:
input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Implement a small neural network with exactly two linear layers
s
output = model(input_tensor)
print(output)

tensor([[1.0580]], grad_fn=<AddmmBackward0>)


In [12]:


input_tensor = torch.tensor([[0.8]])

# Create a sigmoid function and apply it on input_tensor
sigmoid = nn.Sigmoid()
probability = sigmoid(input_tensor)
print(probability)

tensor([[0.6900]])


In [13]:
input_tensor = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])

# Create a softmax function and apply it on input_tensor
softmax = nn.Softmax(dim=-1)
probabilities = softmax(input_tensor)
print(probabilities)

tensor([[1.2828e-01, 1.1698e-04, 5.7492e-01, 3.4961e-02, 1.5669e-01, 1.0503e-01]])


In [67]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

print(model[0].weight.grad)
# Update network below to perform a multi-class classification with four labels
model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6,4), 
  nn.Softmax(dim=-1)
)

output = model(input_tensor)

print(output)

None
tensor([[0.5659, 0.1449, 0.1254, 0.1638]], grad_fn=<SoftmaxBackward0>)


In [70]:
w1=model[0].weight.grad
b2=model[1].bias

print(w1)
print(b2)

None
Parameter containing:
tensor([ 0.0089,  0.2107, -0.0957, -0.0216,  0.0694,  0.0098, -0.0466, -0.1770,
        -0.1327,  0.1570,  0.1772, -0.1185], requires_grad=True)


In [83]:
y = [0]
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])

# Create a one-hot encoded vector of the label y
one_hot_label = F.one_hot(torch.tensor(y), scores.shape[1])

# Create the cross entropy loss function
criterion = nn.CrossEntropyLoss()

# Calculate the cross entropy loss
loss = criterion(scores.double(),one_hot_label.double())
print(loss)

print(one_hot_label)

tensor(5.9619, dtype=torch.float64)
tensor([[1, 0, 0, 0]])


In [18]:
weight=torch.tensor([[-0.4827,  0.1587, -0.3080,  0.2934,  0.2473,  1.7578, -0.1854, -1.1073,
         -0.3659],
        [ 1.1823,  0.0671,  1.0728,  0.5413, -0.5912,  0.4601, -0.6767, -1.4138,
          0.3818]],requires_grad=True)

bias=torch.tensor([1.0090, 0.6352],requires_grad=True)

preds=torch.tensor([[0.3269, 0.9955]],requires_grad=True)

target=torch.tensor([[1., 0.]])

print(target)
print(preds)
print(bias)
print(weight)

tensor([[1., 0.]])
tensor([[0.3269, 0.9955]], requires_grad=True)
tensor([1.0090, 0.6352], requires_grad=True)
tensor([[-0.4827,  0.1587, -0.3080,  0.2934,  0.2473,  1.7578, -0.1854, -1.1073,
         -0.3659],
        [ 1.1823,  0.0671,  1.0728,  0.5413, -0.5912,  0.4601, -0.6767, -1.4138,
          0.3818]], requires_grad=True)


In [19]:
print(bias.grad)
print(bias.grad_fn)
print(bias.is_leaf)

None
None
True


In [20]:
print(preds.grad)
print(preds.grad_fn)
print(preds.is_leaf)


preds2=preds+.01
preds3=preds2.detach().requires_grad_(True).clone()
print(preds2)
print(preds2.is_leaf)
print(preds3)
print(preds3.is_leaf)



None
None
True
tensor([[0.3369, 1.0055]], grad_fn=<AddBackward0>)
False
tensor([[0.3369, 1.0055]], grad_fn=<CloneBackward0>)
False


In [21]:
criterion = nn.CrossEntropyLoss()

loss = criterion(preds3, target)

print(loss)

tensor(1.0823, grad_fn=<DivBackward1>)


In [22]:
loss.backward()


In [23]:
print(weight.grad)
print(bias.grad)

None
None


In [24]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.data)
print(x.grad)
print(x.grad_fn)
print(x.is_leaf)

y = x + 2
print(y)

print(y.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]])
None
None
True
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [5]:
model2 = nn.Linear(5, 3)
print(model2.weight.grad)  # None, since the grads have not been computed yet
print(model2.bias.grad)

x = torch.randn(5, 5)
y = model2(x)
loss2 = y.sum()
loss2.backward()

print(model2.weight.grad)
print(model2.bias.grad)

None
None
tensor([[ 2.9315,  2.0464,  2.3237,  0.4427, -0.0633],
        [ 2.9315,  2.0464,  2.3237,  0.4427, -0.0633],
        [ 2.9315,  2.0464,  2.3237,  0.4427, -0.0633]])
tensor([5., 5., 5.])


In [46]:
print(x)

tensor([[ 0.0708, -1.8378,  1.0154, -0.2302, -0.3061],
        [-0.2677, -0.5898, -0.0361,  0.5323, -0.0360],
        [-0.2767, -0.2589, -0.4566, -1.7090, -1.6011],
        [-0.8597, -2.1341,  0.8951, -0.3863,  1.0991],
        [ 2.1195, -1.1341,  0.8718,  0.3702, -1.1944]])


In [47]:
print(y)

tensor([[ 0.0703,  0.3441,  0.4364],
        [ 0.4659,  0.6237, -0.0457],
        [ 0.3785,  0.4782,  0.3726],
        [ 0.2225,  0.2903,  0.8583],
        [-0.5075,  0.1294, -0.4141]], grad_fn=<AddmmBackward0>)


In [48]:
print(model2.weight)

Parameter containing:
tensor([[-0.4412,  0.2361,  0.1128,  0.1311, -0.1098],
        [-0.2456, -0.0869, -0.1756,  0.2316, -0.2085],
        [-0.2100, -0.2172,  0.0775, -0.2947,  0.0893]], requires_grad=True)


In [49]:
print(model2.weight.grad)

tensor([[ 0.7861, -5.9549,  2.2897, -1.4230, -2.0385],
        [ 0.7861, -5.9549,  2.2897, -1.4230, -2.0385],
        [ 0.7861, -5.9549,  2.2897, -1.4230, -2.0385]])


In [50]:
print(loss2)

tensor(3.7030, grad_fn=<SumBackward0>)
